FROM tinkerpop/gremlin-server:3.8.1

COPY gremlin-server.yaml /opt/gremlin-server/conf/prototype-server.yaml
COPY tinkergraph.properties /opt/gremlin-server/conf/tinkergraph.properties

CMD ["conf/prototype-server.yaml"]

